### ISSUE TITLE
signal SIGSEGV: segmentation violation when running with --format pretty-printer flag

### ISSUE THREAD

**Issue by MMquant** [kubescape/kubescape#1032]
# Bug description
When running kubescape as

```
kubescape scan --enable-host-scan \
          --kubeconfig /mnt/config-k8s-cls-test \
          --verbose \
          --disable-color \
          --format pretty-printer \
          --output output
```

I'm getting this segmentation error

```
...
...
...
| Low      | CIS-4.2.8 Ensure that the --hostname-override argument is not set                                                           |        0         |         0          |       6       |      0%      |
| Low      | CIS-4.2.9 Ensure that the --event-qps argument is set to 0 or a level which ensures appropriate event capture               |        0         |         0          |       6       |      0%      |
+----------+-----------------------------------------------------------------------------------------------------------------------------+------------------+--------------------+---------------+--------------+
|          |                                                      RESOURCE SUMMARY                                                       |        20        |         56         |      172      |    9.96%     |
+----------+-----------------------------------------------------------------------------------------------------------------------------+------------------+--------------------+---------------+--------------+
FRAMEWORKS: MITRE (risk: 2.44), AllControls (risk: 5.62), DevOpsBest (risk: 6.11), NSA (risk: 6.45), ArmoBest (risk: 6.18), cis-v1.23-t1.0.1 (risk: 14.25)

* failed to pull image scanning data: credentials are not configured for any registry adaptor. for more information: https://hub.armosec.io/docs/configuration-of-image-vulnerabilities

[success] Scan results saved. filename: output.txt
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x55dd2f34e847]

goroutine 1 [running]:
github.com/kubescape/kubescape/v2/core/pkg/resultshandling/printer/v2.(*PrettyPrinter).printResourceAttackGraph(0xc000cb8720, {0x0?, 0x0?})
	/work/core/pkg/resultshandling/printer/v2/attacktracks.go:74 +0x27
github.com/kubescape/kubescape/v2/core/pkg/resultshandling/printer/v2.(*PrettyPrinter).printAttackTracks(0xc000cb8720, 0xc0001b9980)
	/work/core/pkg/resultshandling/printer/v2/attacktracks.go:121 +0x748
github.com/kubescape/kubescape/v2/core/pkg/resultshandling/printer/v2.(*PrettyPrinter).ActionPrint(0xc000cb8720, 0xc0001b9980)
	/work/core/pkg/resultshandling/printer/v2/prettyprinter.go:65 +0x25b
github.com/kubescape/kubescape/v2/core/pkg/resultshandling.(*ResultsHandler).HandleResults(0xc00111c400)
	/work/core/pkg/resultshandling/results.go:80 +0xeb
github.com/kubescape/kubescape/v2/cmd/scan.getFrameworkCmd.func2(0x55dd3028c8e0?, {0xc0005ff9d0, 0x1, 0x1})
	/work/cmd/scan/framework.go:111 +0x565
github.com/kubescape/kubescape/v2/cmd/scan.GetScanCommand.func2(0xc0003e7b00?, {0xc00018e2d0?, 0x9?, 0x9?})
	/work/cmd/scan/scan.go:55 +0x89
github.com/spf13/cobra.(*Command).execute(0xc0003e7b00, {0xc00018e120, 0x9, 0x9})
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003e6c00)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/kubescape/kubescape/v2/cmd.Execute()
	/work/cmd/root.go:87 +0x2d
main.main()
	/work/main.go:9 +0x1d
```

Testing other output types works as intended.

Also note that an `output.txt` file is created regardless the error.
The output content is

```
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Controls: 166 (Failed: 46, Excluded: 27, Skipped: 3)
Failed Resources by Severity: Critical — 0, High — 44, Medium — 74, Low — 22

+----------+---------------------------------------------------------------------------------------------------------------------------+------------------+--------------------+---------------+--------------+
| SEVERITY |                                                       CONTROL NAME                                                        | FAILED RESOURCES | EXCLUDED RESOURCES | ALL RESOURCES | % RISK-SCORE |
+----------+---------------------------------------------------------------------------------------------------------------------------+------------------+--------------------+---------------+--------------+
| High     | Resources memory limit and request                                                                                        |        2         |         10         |      13       |     14%      |
| High     | Resource limits                                                                                                           |        2         |         11         |      13       |     14%      |
| High     | List Kubernetes secrets                                                                                                   |        0         |         3          |      18       |      0%      |
...
...
...
FRAMEWORKS: MITRE (risk: 2.44), AllControls (risk: 5.62), DevOpsBest (risk: 6.11), NSA (risk: 6.45), ArmoBest (risk: 6.18), cis-v1.23-t1.0.1 (risk: 14.25)
* failed to pull image scanning data: credentials are not configured for any registry adaptor. for more information: https://hub.armosec.io/docs/configuration-of-image-vulnerabilities

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Name: calico-node
Kind: DaemonSet
Namespace: kube-system

Score: 6330.50
Severity: High
Total vectors: 26
```

# Environment
Official docker image quay.io/kubescape/kubescape

# Steps To Reproduce
```
# On host machine run
$ docker run -it --rm --entrypoint sh -v ${PWD}:/mnt quay.io/kubescape/kubescape
# In container run
$ kubescape scan --enable-host-scan \
          --kubeconfig /mnt/config-k8s-cls-test \
          --verbose \
          --disable-color \
          --format pretty-printer \
          --output output
```

# Expected behavior
1. No errors.
2. When `--output file.txt` flag is specified I would expect the `file.txt` to be created, not `file.txt.txt`
3. When `--verbose` flag is specified I would expect the output file to contain verbose output.

# Actual Behavior
1. Getting a segmentation violation error.
2. Kubescape creates `output.txt.txt` file.
3. Kubescape outputs only scan summary table.

**Comment by matthyx** [comment]
@MMquant can you check the version of `kubescape` running in your container?
You might want to `docker pull` again and check with the latest version which is `v2.0.182`.

**Comment by MMquant** [comment]
Hi @matthyx,
I tested it on v2.0.182 and kubescape behaves exactly the same like v2.0.181

**Comment by matthyx** [comment]
Thanks for checking, let me investigate.

**Comment by matthyx** [comment]
@MMquant the problem appears when you combine `--verbose` with `--format pretty-printer`.
I have a "fix" but I am not sure if it cures the original problem or just its consequences... I will have to check with @amirmalka

**Comment by dwertent** [comment]
> When --output file.txt flag is specified I would expect the file.txt to be created, not file.txt.txt

@vladklokun Please take a look

**Comment by vladklokun** [comment]
@dwertent on it :eyes: 

@MMquant Hi! Your expectation makes sense to me. However, we support emitting multiple outputs via the same flags, too. So I’m on edge how to keep the invocation consistent across single and multiple output modes.

So keeping that in mind, what would you expect when running the following commands?

```
kubescape scan --output file --format pretty-printer
kubescape scan --output file --format pretty-printer,json,sarif
kubescape scan --output file.txt --format pretty-printer,json,sarif
```

**Comment by MMquant** [comment]
@vladklokun Hi,
I understand.
I didn't know that you can pass multiple format options to the `--format` flag. It's not clear from the docs.
Now it makes sense to me to leave it as it is. This mutliple output option is very handy.

**Comment by vladklokun** [comment]
@MMquant Thank you! I appreciate you finding multiple outputs handy.

You bring up a good point regarding documentation. I will try to improve our existing `kubescape scan --help` docs.

If we mentioned that `--output` controls the name of the output file without the extension, and that we also support outputting to multiple formats in this help message, would you find that helpful?

**Comment by MMquant** [comment]
For example let's see the `--help` example here https://github.com/ffuf/ffuf. If a flag supports multiple values they are describing the flag as
```
Comma separated list of sizes and ranges
Comma separated list of extensions
Comma separated list of <whatever you want>
```
So something like 

```
Comma separated list of output formats
```

and

```
Output file name without extension
Output filename without extension
```
could work.
